# SpringBootとVueとPostgreSQLをDockerで動かす
version: '3'
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/${DB_HOST}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  #client:
  #  build: ./client
  #  ports: "8081:8081"
  #  depends_on:
  #    - api
volumes:
  pgdata:
